import { Todo } from "../../types";

export const todos: Todo[] = [
  {
    id: "t1",
    type: "todo",
    title: "Get the milk",
    description: "Walk to the nearby store, bargain and buy the milk.",
    tags: ["today", "routine"],
    createdAt: Date.now(),
  },
  {
    id: "t2",
    type: "todo",
    title: "Exercise for 10 hours",
    description: "Auto added. Do this everyday.",
    tags: ["routine"],
    createdAt: Date.now() - 110000000,
  },
  {
    id: "t3",
    type: "todo",
    title: "Feed the lions",
    description: "Buy some meat. Feed the lions. Sleep next to them.",
    tags: ["zoo", "danger", "skunkworks"],
    createdAt: Date.now() - 210000000,
  },
  {
    id: "t4",
    type: "todo",
    title: "Lorem ipsum must sit somewhere",
    description: "Walk to the nearby store, bargain and buy the milk.",
    tags: ["today", "routine"],
    createdAt: Date.now(),
  },
  {
    id: "t5",
    type: "todo",
    title: "Create gitsta markdown notes",
    description: "Auto added. Do this everyday.",
    tags: ["routine", "skunkworks"],
    createdAt: Date.now() - 110000000,
  },
  {
    id: "t6",
    type: "todo",
    title: "Discuss the Secure ScuttleButt API",
    description: "Buy some meat. Feed the lions. Sleep next to them.",
    tags: ["zoo", "danger", "skunkworks"],
    createdAt: Date.now() - 210000000,
  },
  {
    id: "t7",
    type: "todo",
    title: "Solid Discussion",
    description: "Walk to the nearby store, bargain and buy the milk.",
    tags: ["today", "routine"],
    createdAt: Date.now(),
  },
  {
    id: "t8",
    type: "todo",
    title: "Blah blah go to the park",
    description: "Auto added. Do this everyday.",
    tags: ["routine", "skunkworks"],
    createdAt: Date.now() - 110000000,
  },
];
